app/models.py
# -*- coding: utf-8 -*-
# @Author: huerke
# @Date:   2016-09-03 10:39:52
# @Last Modified by:   huerke
# @Last Modified time: 2016-09-04 12:58:27
from datetime import datetime
import hashlib
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app, request
from flask_login import UserMixin, AnonymousUserMixin
from . import db, login_manager


class Jishuqu(db.Model):
    __tablename__ = 'jishuqu'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Text, unique=True)
    link = db.Column(db.Text, unique=True)

    def __repr__(self):
        return '<Jishuqu %r>' % self.title


class Dagaier(db.Model):
    __tablename__ = 'dagaier'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Text, unique=True)
    link = db.Column(db.Text, unique=True)

    def __repr__(self):
        return '<Dagaier %r>' % self.title


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    confirmed = db.Column(db.Boolean, default=False)

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        return True

    def generate_reset_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'reset': self.id})

    def reset_password(self, token, new_password):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('reset') != self.id:
            return False
        self.password = new_password
        db.session.add(self)
        return True

    def generate_email_change_token(self, new_email, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'change_email': self.id, 'new_email': new_email})

    def change_email(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('change_email') != self.id:
            return False
        new_email = data.get('new_email')
        if new_email is None:
            return False
        if self.query.filter_by(email=new_email).first() is not None:
            return False
        self.email = new_email
        db.session.add(self)
        return True

    def __repr__(self):
        return '<User %r>' % self.username


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
# -*- coding: utf-8 -*-
# @Author: huerke
# @Date:   2016-09-03 10:55:43
# @Last Modified by:   huerke
# @Last Modified time: 2016-09-03 11:21:34
from flask_wtf import Form
from wtforms import StringField, TextAreaField, BooleanField, SelectField,\
    SubmitField
from wtforms.validators import Required, Length, Email, Regexp
from wtforms import ValidationError


class KeyForm(Form):
    key = StringField('请输入标题关键字', validators=[Required()])
    submit = SubmitField('提交')

app/__init__.py
# -*- coding: utf-8 -*-
# @Author: huerke
# @Date:   2016-09-03 10:42:22
# @Last Modified by:   huerke
# @Last Modified time: 2016-09-03 13:24:02
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_pagedown import PageDown
from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
pagedown = PageDown()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    with app.test_request_context():
        db.create_all()
    login_manager.init_app(app)
    pagedown.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
# -*- coding: utf-8 -*-
# @Author: huerke
# @Date:   2016-09-03 10:55:15
# @Last Modified by:   huerke
# @Last Modified time: 2016-09-03 10:58:28
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
# -*- coding: utf-8 -*-
# @Author: huerke
# @Date:   2016-09-03 10:55:34
# @Last Modified by:   Administrator
# @Last Modified time: 2016-09-05 10:04:29
from flask import render_template, redirect, url_for, abort, flash, request,\
    current_app, session
from flask_login import login_required, current_user
from . import main
from .forms import KeyForm
from .. import db
from ..models import Jishuqu, Dagaier
from ..get1024addr import caoliuaddr
domain_name = caoliuaddr
import sys
reload(sys)
sys.setdefaultencoding('utf-8')


@main.route('/')
def index():
    return render_template('index.html', domain_name=domain_name)


@main.route('/jishu', methods=['GET', 'POST'])
@login_required
def jishu():
    form = KeyForm()
    result = ''
    if form.validate_on_submit():
        key = form.key.data
        result = Jishuqu.query.filter(
            Jishuqu.title.like('%' + key + '%')).all()
        if not result:
            flash('未找到相关结果')
    return render_template('jishu.html', form=form, result=result, domain_name=domain_name)


@main.route('/dagaier', methods=['GET', 'POST'])
@login_required
def dagaier():
    form = KeyForm()
    result = ''
    if form.validate_on_submit():
        key = form.key.data
        result = Dagaier.query.filter(
            Dagaier.title.like('%' + key + '%')).all()
        if not result:
            flash('未找到相关结果')
    return render_template('dagaier.html', form=form, result=result, domain_name=domain_name)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}CL{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">CL</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('auth.change_email_request') }}">Change Email</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/dagaier.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}查询达盖尔区标题{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>请在下面表单内输入标题关键字!</h1>
</div>
{{ wtf.quick_form(form) }}
{% if result %}

<table class="table table-striped">
  <tr>
    <th>id</th>
    <th>title</th>
  </tr>
   {% for res in result %}
<tr>
  <td>{{ res.id }}</td>
  <td><a href="{{ domain_name + res.link }}">{{ res.title }}</a></td>
</tr>


   {% endfor %}

</table>

 

{% endif %}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}草榴游客搜索系统{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>欢迎来到草榴游客搜索系统!</h1>
</div>
{% if current_user.is_authenticated %}
<li><a href="{{ domain_name }}" target="_blank">获取草榴最新网址</a></li>
<li><a href="{{ url_for('main.jishu') }}" target="_blank">查询技术讨论区帖子</a></li>
<li><a href="{{ url_for('main.dagaier') }}" target="_blank">查询达盖尔区帖子</a></li>

{% else %}

<p>请点击右上角登陆</p>      




{% endif %}
{% endblock %}

app/templates/jishu.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}查询技术讨论区标题{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>请在下面表单内输入标题关键字!</h1>
</div>
{{ wtf.quick_form(form) }}
{% if result %}


<table class="table table-striped">
  <tr>
    <th>id</th>
    <th>title</th>
  </tr>
   {% for res in result %}
<tr>
  <td>{{ res.id }}</td>
  <td><a href="{{ domain_name + res.link }}">{{ res.title }}</a></td>
</tr>


   {% endfor %}

</table>

 

{% endif %}
{% endblock %}